version: '3.8'
services:
        ebook:
             build: .
             container_name: fs-s2-integrasi
             image: registry.mejik.xyz/ebook/fs-s2-integrasi
             ports:
                     - 3008:3000